### ISSUE TITLE
Multi-categories

### ISSUE THREAD

**Issue by ghost** [NatalieMac/html5-css3-jquery#1]
Hi!
Thank you very much for this helpful code!
I have a question. How can I put an object in more than one data-cat?
For example, I want an object both in category "a" and "b".
Thank you!

**Comment by NatalieMac** [comment]
There would be several ways to go about it - take a look at other solutions like Isotope (http://isotope.metafizzy.co/) and MixItUp (https://mixitup.kunkalabs.com/) to get some ideas.

This code in this repository was just a demo during a short talk - it wasn't meant to be production-ready code.
